export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const INCREASE_CART_ITEM_COUNT = 'INCREASE_CART_ITEM_COUNT';
export const DECREASE_CART_ITEM_COUNT = 'DECREASE_CART_ITEM_COUNT';
